### ISSUE TITLE
moby build always seems to pull

### ISSUE THREAD

**Issue by rneugeba** [moby/tool#57]
Sometime towards the end of last week `moby build` always started to pull images from hub even if the image was available in the local docker instance. For example:
```
% moby version
moby version 0.0
commit: b822bff6adcf03408ec019dfee9401fb58624951
% docker images linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
REPOSITORY          TAG                                        IMAGE ID            CREATED             SIZE
linuxkit/init       1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037   8bf318bfb8fe        32 hours ago        1.46MB
% moby build linuxkit
Pull kernel image: linuxkit/kernel:4.9.x
Extract kernel image: linuxkit/kernel:4.9.x
Pull image: linuxkit/kernel:4.9.x
Add init containers:
Process init image: linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
Pull image: linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
...
```
This pulled `linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037` even though its locally available. This slows down `moby builds` a lot.

I haven't had time to bisect, but I think it was sometime around the trust fixes.

/ping @riyazdf

**Comment by riyazdf** [comment]
with `trust` enabled we're doing a name conversion with a notary request, and then issuing a `cli.ImagePull` request which may pull down the image if it isn't already pulled into local storage.

I think in most cases the extra slowdown is on the first pull into image cache or lookup against notary, I'm in the process of investigating this.  We can also split out the pull logic to be exclusively in `--pull`, such that the notary translation and actual image pull for that (potentially) new reference are decoupled.

**Comment by rneugeba** [comment]
we had some YML files with `trust` sections before and they didn't pull the images listed, so something changed

**Comment by justincormack** [comment]
Is this fixed? Or is it related to #62? I am a bit confused... I thought this was going to be simple as Docker gets this right.

**Comment by rneugeba** [comment]
this may get fixed with your latest update on linuxkit. but current tip still pulls

**Comment by justincormack** [comment]
No, its not fixed by that. Disabling wifi when I have all the images cached I get
```
Pull kernel image: linuxkit/kernel:4.9.x
FATA[0000] Could not pull image linuxkit/kernel:4.9.x: Trusted pull for linuxkit/kernel:4.9.x failed: Get https://notary.docker.io/v2/: dial tcp: lookup notary.docker.io on [::1]:53: read udp [::1]:57348->[::1]:53: read: connection refused 
```

It works if I use `moby build -disable-content-trust=true linuxkit.yml` but it makes it somewhat annoying for working offline.

**Comment by riyazdf** [comment]
I've been looking into this:
- If you already have the image locally, docker won't actually do a pull from the registry, but the print still appears from the tool
- on #62 it does reduce the number of trust lookups, but there is still one online call to check if this is the latest version of the repo
- @justincormack you are correct that the tool should be able to leverage full caching like docker so that offline builds with trust will succeed.  I'm tracking down the issue in the tool and will put up a PR

**Comment by justincormack** [comment]
It would help to remove the pull message if there is no pull, as it makes the output very cluttered...

**Comment by riyazdf** [comment]
@justincormack: agree, I plan to open a PR for the offline cases fixes and pull output later today :+1:
